language: go

# Travis does not come with dep pre-installed. Thus, we must install it.
# Versions can be found on https://github.com/golang/dep/releases.
env:
  - DEP_VERSION="0.5.0"
before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install: script/bootstrap
script:
- script/test
- script/build
